### PR TITLE
Responsive Tables

### PR DESCRIPTION
**Pull request by cpastre1**
Tables now rearrange on mobile to be more readable.

### CODE REVIEW

**Comment by tvanantwerp** [comment]
Let me poke at this. I want to see if there's a way to do it without `data-title` attributes, since that would presently be added manually.

**Comment by tvanantwerp** [comment]
So we could use JavaScript to dynamically set `data-title` attributes. It would have to:

1) Select each `table` on the page.
2) Select each `th` in the `thead` of the `table`, and extract the text.
3) Select each `tr` in `tbody` and check the number of `td`s against the length of the extracted header text array.
4) If the numbers match, set each `data-title` for each `td` with the `th` text of the corresponding index.

Lots of existing TF tables are weird and may not work right with this approach. None of them will work with the currently proposed approach of using only CSS.

**Comment by tvanantwerp** [comment]
I've got a simplified version of the responsive tables working with JavaScript setting `data-title` attributes on `td`s throughout the table. It checks to make sure that the number of `th`s in the `table` matches the `td`s in a row, just in case the table is weird in its layout.

**Comment by cpastre1** [comment]
This is great. I'll do a little more testing this morning, restyle a few things, and then I think we might be good to merge. 

As for existing TF tables, my inclination is that we leave those for now (or maybe just allow a horizontal scroll), and implement this for new tables.

**Comment by tvanantwerp** [comment]
The JS will apply the responsive properties to any simple table with an equal number of `th` in `thead` as `td` in each row. So any older table matching that simple structure will be responsive. Only weird customized tables won't work that way.

**Comment by cpastre1** [comment]
Will weird tables get screwed up because of this, or will the responsive styles just not be applied?

**Comment by tvanantwerp** [comment]
It just won't be applied. The JS only adds responsive attributes if the counts match, implying a straightforward structure.

**Pull request merged**
