### PR TITLE
Modularize link lists

### PR DESCRIPTION
**Pull request by tvanantwerp**
Rewrote the lists of link to related posts, as seen on category and tag pages.

### CODE REVIEW

**Comment by cpastre1** [comment]
We should probably just add section titles outside of the link-list partial to avoid situations like this:

image

**Comment by cpastre1** [comment]
For some reason the list on the category template page isn't centered despite `column--centered` being applied 

image

**Comment by tvanantwerp** [comment]
Everything seems to be full width, though I can't find a specific CSS declaration that explains why it would be...

**Comment by tvanantwerp** [comment]
Looks the same for me on `master` so I'm not sure how it's supposed to look.

**Comment by cpastre1** [comment]
Ideally, it would be centered like below. Let me play with it a little

image

**Comment by cpastre1** [comment]
I added columns on either side of the category page post list in order to center it: 
image

**Comment by tvanantwerp** [comment]
This can look very narrow at certain screen sizes. Maybe 30%/30% side margins on desktop is too much?

image

**Comment by cpastre1** [comment]
Just changed the side margins back to 25% width. I think this looks like a good width. Anything more narrow and the list ends up looking strangely off-center on wider screens
image

**Pull request merged**
